server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: 124.222.60.243:8848 # nacos地址
      discovery:
        ip: 124.222.66.170
        cluster-name: SH # 集群名称
    gateway:
      routes: # 网关路由配置
        - id: auth-service
          uri: lb://authservice
          predicates:
            - Path=/auth/**
        - id: docker-service
          uri: lb://dockerservice
          predicates:
            - Path=/docker/**
        - id: zuul-service
          uri: lb://zuul
          predicates:
            - Path=/zuul/**
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
              - "http://localhost:3000"
              - "http://124.222.66.170"
              - "http://124.222.60.243"
              - "http://139.224.190.128"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期

feign:
  client:
    config:
      default: # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
        loggerLevel: BASIC #  日志级别
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
#  sentinel:
#    enabled: true

auth:
  secret: cong0917
  pubKeyPath: E:\桌面\edge_of_computing\cloud-edgeCompute\auth-service\src\main\resources\static # 公钥地址